In [1]:
import numpy as np

## DataTypes and Attributes

In [2]:
## Numpy's main datatype is ndarray
a1 =  np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2.0,3.3],
             [4,5,6.7]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.7]])

In [7]:
a3 = np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
               [[10,11,12],
               [13,14,15],
               [16,17,18]]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a1.shape

(3,)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a2.shape

(2, 3)

In [12]:
a1.ndim

1

In [13]:
a2.ndim

2

In [14]:
a3.ndim

3

In [15]:
a3.size

18

In [16]:
a3.dtype

dtype('int32')

In [17]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.7]])

In [20]:
## Create a DataFrame from Numpy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.7

## 2. Creating arrays

In [23]:
ones = np.ones((2,3), dtype=int)

In [24]:
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [25]:
ones.dtype

dtype('int32')

In [26]:
zeros = np.zeros((2,3))

In [27]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
zeros.dtype

dtype('float64')

In [31]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [32]:
random_array = np.random.randint(0,10, size=(3,5))
random_array

array([[2, 7, 1, 6, 0],
       [3, 6, 0, 0, 7],
       [3, 5, 3, 7, 7]])

## Pseudo random numbers - seed

In [44]:
np.random.seed(seed=0)
random_array_2= np.random.randint(10, size=(5,3))
random_array_2

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [45]:
random_array_3 = np.random.random((5,3))

In [46]:
random_array_3

array([[0.79172504, 0.52889492, 0.56804456],
       [0.92559664, 0.07103606, 0.0871293 ],
       [0.0202184 , 0.83261985, 0.77815675],
       [0.87001215, 0.97861834, 0.79915856],
       [0.46147936, 0.78052918, 0.11827443]])

## 3. Viewing arrays and matrices

In [49]:
np.unique(random_array_2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
a1

array([1, 2, 3])

In [51]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.7]])

In [52]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [53]:
a1[0]

1

In [54]:
a2[0]

array([1. , 2. , 3.3])

In [55]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[0, 1, 9, 9, 0],
         [4, 7, 3, 2, 7],
         [2, 0, 0, 4, 5],
         [5, 6, 8, 4, 1]],

        [[4, 9, 8, 1, 1],
         [7, 9, 9, 3, 6],
         [7, 2, 0, 3, 5],
         [9, 4, 4, 6, 4]],

        [[4, 3, 4, 4, 8],
         [4, 3, 7, 5, 5],
         [0, 1, 5, 9, 3],
         [0, 5, 0, 1, 2]]],


       [[[4, 2, 0, 3, 2],
         [0, 7, 5, 9, 0],
         [2, 7, 2, 9, 2],
         [3, 3, 2, 3, 4]],

        [[1, 2, 9, 1, 4],
         [6, 8, 2, 3, 0],
         [0, 6, 0, 6, 3],
         [3, 8, 8, 8, 2]],

        [[3, 2, 0, 8, 8],
         [3, 8, 2, 8, 4],
         [3, 0, 4, 3, 6],
         [9, 8, 0, 8, 5]]]])

## 4.Manipulating and comparing arrays

## Arithmetic

In [57]:
a1

array([1, 2, 3])

In [58]:
ones = np.ones(3, dtype=int)

In [59]:
ones

array([1, 1, 1])

In [60]:
a1 + ones

array([2, 3, 4])

In [61]:
a1 - ones

array([0, 1, 2])

In [62]:
a4= np.random.randint(10, size=(3,3))

In [63]:
a4

array([[9, 0, 9],
       [6, 5, 3],
       [1, 8, 0]])

In [70]:
a5= np.random.randint(10, size=(3,3))

In [71]:
a5

array([[3, 6, 5],
       [7, 0, 8],
       [4, 6, 5]])

In [72]:
a4-a5

array([[ 6, -6,  4],
       [-1,  5, -5],
       [-3,  2, -5]])

In [74]:
a4

array([[9, 0, 9],
       [6, 5, 3],
       [1, 8, 0]])

In [75]:
a5

array([[3, 6, 5],
       [7, 0, 8],
       [4, 6, 5]])

In [73]:
a4 * a5

array([[27,  0, 45],
       [42,  0, 24],
       [ 4, 48,  0]])

## Aggregation

In [76]:
listy_list = [1,2,3,4]

In [77]:
type(listy_list)

list

In [78]:
sum(listy_list)

10

In [79]:
a1

array([1, 2, 3])

In [80]:
np.sum(a1)

6

In [81]:
massive_array = np.random.random(1000)

In [82]:
massive_array[:10]

array([0.1494483 , 0.86812606, 0.16249293, 0.61555956, 0.12381998,
       0.84800823, 0.80731896, 0.56910074, 0.4071833 , 0.069167  ])

In [83]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

72.1 µs ± 1.86 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
4.29 µs ± 310 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [84]:
72.1/4.29

16.806526806526804

In [85]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.7]])

In [86]:
np.mean(a2)

3.6666666666666665

In [87]:
np.max(a2)

6.7

## Reshaping and transposing

In [88]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.7]])

In [89]:
a2.shape

(2, 3)

In [90]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [92]:
a3.shape

(2, 3, 3)

In [99]:
a2.reshape(2,3,1)

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.7]]])

In [100]:
a2_reshape = a2.reshape(2,3,1)

In [101]:
a2_reshape

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.7]]])

In [102]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [107.2, 113.9, 120.6]]])

In [103]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.7]])

In [104]:
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.7]])

In [105]:
a2.T.shape

(3, 2)

## Dot product

In [106]:
np.random.seed(0)
mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [109]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [110]:
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [111]:
mat1.T

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]])

In [112]:
mat1.T.shape

(3, 5)

In [114]:
mat2.shape

(5, 3)

In [116]:
mat1_new = mat1.T

In [118]:
mat1_new.shape

(3, 5)

In [119]:
np.dot(mat1_new, mat2)

array([[121, 114,  77],
       [153, 108,  80],
       [135,  69,  84]])

## Dot product (nut jars sold)

In [120]:
np.random.seed(0)
sales_amount = np.random.randint(20, size=(5,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [121]:
# create weekly sales dataframe
weekly_sales = pd.DataFrame(sales_amount,
                            index=['Mon', 'Tue', 'Wed', 'Thur', 'Fri'],
                            columns=['Almond butter', 'Peanut butter', 'Cashew butter'] )
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon              12             15              0
Tue               3              3              7
Wed               9             19             18
Thur              4              6             12
Fri               1              6              7

In [122]:
# prices
prices = np.array([10,8,12])

In [123]:
prices

array([10,  8, 12])

In [126]:
butter_prices = pd.DataFrame(prices.reshape(1,3),
                           index=['Prices'],
                           columns=['Almond butter', 'Peanut butter', 'Cashew butter'])
butter_prices

Almond butter  Peanut butter  Cashew butter
Prices             10              8             12

In [127]:
# shapes aren't aligned let's transpose
total_sales = np.dot(sales_amount, butter_prices.T)

In [128]:
total_sales

array([[240],
       [138],
       [458],
       [232],
       [142]])

In [129]:
weekly_sales['Total ($)'] = total_sales

In [130]:
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total ($)
Mon              12             15              0        240
Tue               3              3              7        138
Wed               9             19             18        458
Thur              4              6             12        232
Fri               1              6              7        142

## Comparison operators

In [131]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [132]:
a1>=a2

array([[ True,  True, False],
       [False, False, False]])

## 6. Practical Example

<img src="images/panda.png"/>

In [136]:
# turn an image into an array
import matplotlib.pyplot as plt

In [138]:
from matplotlib.image import imread

In [139]:
panda = imread("images/panda.png")
type(panda)

numpy.ndarray

In [141]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)